version: '3.8'

services:
  rust:
    build: .
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://root:password@mongodb:27017
    networks:
      local:
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      local:
        aliases:
          - mongodb
networks:
  local: